### PR TITLE
Fixes cache in CI

### PR DESCRIPTION
**Pull request by artplan1**
- fixes cache using option in step https://github.com/ruby/setup-ruby#caching-bundle-install-automatically
- running appraisals as matrix, like in https://github.com/ruby/setup-ruby/issues/73

### CODE REVIEW

**Comment by artplan1** [comment]
hey @excid3,
I split tests to workflows for each ruby/rails versions. Lmk what you think about this approach

**Comment by excid3** [comment]
This looks great @artplan1 🙏

**Comment by artplan1** [comment]
@excid3 I see that sqlite installation step says that is already installed, maybe we can 🔪 it?

image

**Comment by excid3** [comment]
Yeah! That'd be super nice.

**Pull request merged**
