### PR TITLE
Allow setting a custom primary key

### PR DESCRIPTION
**Pull request by ArthurWD**
I would like to be able to set the primary key of the tenant. Is this PR acceptable?

### CODE REVIEW

**Comment by ErwinM** [comment]
look goods, thx!

**Comment by ErwinM** [comment]
Would you mind adding a little snippet to the readme about this? Thx!

**Comment by ArthurWD** [comment]
Thanks!

I've added a PR for the readme

**Comment by rtdp** [comment]
Would really appreciate this PR published to Rubygems. Thanks!

**Pull request merged**
