### PR TITLE
Allow `inverse_of` to be used in the `acts_as_tenant` declaration.

### PR DESCRIPTION
**Pull request by lowjoel**
Can be useful for ActiveRecord in preventing duplicate queries.

### CODE REVIEW

**Comment by SkylerLipthay** [comment]
:+1: Would love to see this accepted!

**Comment by lowjoel** [comment]
Hi @ErwinM, any comments on this PR?

**Comment by ErwinM** [comment]
I'm on a summer break without laptops (imagine that!)I'll have a look when I get back                                                                                                                                                                                                                                                                                                                                        Erwin                                                                                                                                                                                                                From: Joel LowSent: Tuesday, 11 August 2015 06:27To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantCc: ErwinMSubject: Re: [acts_as_tenant] Allow `inverse_of` to be used in the `acts_as_tenant` declaration. (#120)Hi @ErwinM, any comments on this PR?

—Reply to this email directly or view it on GitHub.

**Comment by lowjoel** [comment]
Sounds fun :) I’ll wait for your comments when you get back.

**Comment by lowjoel** [comment]
@ErwinM just a gentle nudge, in case you've forgot about this...

**Comment by ErwinM** [comment]
@lowjoel thx for this and apologies my summer break went on for a bit there..

**Comment by lowjoel** [comment]
Thanks! Hope you had fun :)

**Pull request merged**
