### PR TITLE
Mongoid compatibility

### PR DESCRIPTION
**Pull request by iangreenleaf**
Since this plugin is mostly based on the ActiveModel interface, it doesn't take a ton of work to integrate it with an alternative to ActiveRecord like Mongoid. Most of the problems I encountered were little things, like:

1. Not requiring active_record automatically - if Rails is using it, it should already be present.
2. Not assuming that model classes will follow the ActiveRecord inheritance scheme.

With these changes, I have basic multitenancy working with Mongoid. My models declare scope like this:

```ruby
class Comment
  include Mongoid::Document
  include ActsAsTenant::ModelExtensions
  belongs_to :tenant
  acts_as_tenant :tenant
end
```

Related: #10.

### CODE REVIEW

**Comment by ErwinM** [comment]
Could you add some tests to it or someone (probably me) will break this in the future.

With tests im ok with pulling this in, but I have no experience with Mongoid so I would be tagging you in all questions related to it..

And out of curiosity: what is the reasoning behind putting some methods into a module and then including it?

**Comment by iangreenleaf** [comment]
Yeah, I'll look into adding Mongo tests (or really, into providing a mechanism to run the test suite against Mongo as well as SQL). Wasn't gonna bother until I knew you were interested :)

> And out of curiosity: what is the reasoning behind putting some methods into a module and then including it?

Huh, at the time I thought I needed it to work with Mongoid's inheritance chain, but looking at it again it doesn't seem necessary. I think it would still be a positive to have, though, since it makes the ActsAsTenant methods a part of the inheritance chain, and allows overriding like this:

```ruby
class Blog < Whatever
  acts_as_tenant :account

  def account=(account)
    do_something_else_with(account)
    super # this calls the ActsAsTenant version
  end
end
```

**Comment by iangreenleaf** [comment]
Good thing you asked for tests. Running the existing test suite against Mongoid revealed some other problems I hadn't encountered yet, as well as helping me track down a problem that had been annoying me.

Pushed a bunch of updates. There's now a `rake spec:all` task that will run the specs against both ActiveRecord and Mongoid, and Travis is using that task.

**Comment by iangreenleaf** [comment]
Ping on this. Tests are good and it's ready to go if you like it!

**Comment by ErwinM** [comment]
Thx for this. Looks good to me. Fair bit of work as well to rewire the tests as well! Could you add a few lines in the read me on how this works with mongoid?

**Pull request merged**
