### PR TITLE
Set GitHub Workflow for multiple DB's

### PR DESCRIPTION
**Pull request by MatthewKennedy**

### CODE REVIEW

**Comment by excid3** [comment]
Was thinking about it this morning, since ActsAsTenant doesn't really have any database dependencies (it just adds a belongs_to), do you think we'll get any value out of testing against multiple databases?

**Comment by MatthewKennedy** [comment]
I'll close this PR.

**Comment by excid3** [comment]
@MatthewKennedy sorry for the trouble! We definitely could use ruby head added to Actions.

**Comment by excid3** [comment]
Forgot I had a PR for Ruby 3.0 in my fork, but it wasn't passing so I had left it. Gonna see if preview2 works better.

**Comment by MatthewKennedy** [comment]
@excid3 Not a problem, if truth be told I was experimenting with the GitHub Actions, and thought it might be useful on this gem, but MySQL is proving a little troublesome to get working.

**Comment by excid3** [comment]
Yeah, not quite sure why it was giving you trouble. 

If you want to experiment some more with Actions, here's the PR for Ruby head. I am not sure why it's not passing. Maybe they don't have preview2 in the ruby action yet?
https://github.com/excid3/acts_as_tenant/pull/9/files

**Pull request closed without merging**
