### PR TITLE
Preserve current tenant through active job

### PR DESCRIPTION
**Pull request by tvongaza**
Add a new ActiveJobExtensions which hooks into the serialization and deserialization of an ActiveJob to preserve the current tenant through ActiveJob.

We are using this with GoodJob, though as it is hooking into ActiveJob I'd imagine it should work with any job processor which is ActiveJob compatible.

### CODE REVIEW

**Comment by drale2k** [comment]
@excid3 any opinion on this? Looking to switch to GoodJob, would be cool to have this merged

**Comment by tvongaza** [comment]
> @excid3 any opinion on this? Looking to switch to GoodJob, would be cool to have this merged 

@drale2k I outlined how to patch your rails install to make use of this here if you want to use it in the meantime. https://github.com/ErwinM/acts_as_tenant/issues/321#issuecomment-1741193321

**Comment by excid3** [comment]
I like this. I think we'll want to undo the PR that automatically integrates with Sidekiq since this would double include the tenant in the params which doesn't need to happen.

**Comment by mintuhouse** [comment]
What is the recommended way to disable this?
(We have custom active job extension which does this and few other things)

**Comment by excid3** [comment]
Not at the moment. Just remove that portion from your extension?

**Comment by tvongaza** [comment]
@joshforbes Interesting race condition. I wonder, is the job being created inside a transaction where you're also setting the current_tenant with that just created organization? If so, could you try moving the job creation to an "after_commit" hook?

Otherwise I'm not sure how the code could trigger as we only set the jobs `current_tenant` if the `ActsAsTenant.current_tenant` is also set. It *should* safely fall through if `current_tenant` is not set:
https://github.com/ErwinM/acts_as_tenant/pull/319/files#diff-60903dedf4130718f440a247fc1986aa1784edfdb96db1a71e146d6d01dd6f46R4

Mind sharing some specific code, or better yet add to the test case?
https://github.com/ErwinM/acts_as_tenant/blob/master/spec/jobs/active_job_extensions_spec.rb

**Comment by tvongaza** [comment]
@joshforbes Interesting race condition, and as you've mentioned you have work arounds.

The problem seems to stem from `GlobalID::Locator.locate` returning nil if it fails to find the tenant. Maybe we should raise an exception here if the job's `current_tenant` value is set, but the tenant can't be found. We *are* expecting a tenant to be set in this case, so throwing an exception seems reasonable.

GlobalId's docs for reference: https://github.com/rails/globalid

Should be a reasonably easy change to the following if you want to create a PR:
https://github.com/ErwinM/acts_as_tenant/blob/master/lib/acts_as_tenant/active_job_extensions.rb#L9

Be sure to add a test case:
https://github.com/ErwinM/acts_as_tenant/blob/master/spec/jobs/active_job_extensions_spec.rb

**Pull request merged**
