### PR TITLE
Add fallback

### PR DESCRIPTION
**Pull request by zenkalia**
When trying to use `acts_as_tenant` I found that I wanted some of my models to not be associated with a tenant so that they could be used as a fallback when the tenant is unknown.

As the gem is currently written, setting the `tenant_id` to nil on a model will make it not show up and this PR would make it so if you set `config.allow_fallback = true` then if you do something like `@tenant.models` then you'll get your tenant's associated models AND any models without tenants set.

### CODE REVIEW

**Comment by zenkalia** [comment]
oh it's failing for mangoes. let's see.

**Comment by zenkalia** [comment]
@ErwinM i haven't done a version bump yet, would you like me to do that?

**Comment by pedrofs** [comment]
I like it, but I think the configuration should works in a per model basis. Perhaps passing it to the `acts_as_tenant` method?

@zenkalia what do you think?

@ErwinM any chance to go ahead with that?

**Comment by ErwinM** [comment]
I pulled in Pedrofs changes in #150 which handles this use case.

**Comment by zenkalia** [comment]
My busy-ness worked in my favor. Horay.

**Pull request closed without merging**
