### PR TITLE
Remove sqlite installation step

### PR DESCRIPTION
**Pull request by artplan1**
- Remove sqlite installation step
- Prettify CI step names

### CODE REVIEW

**Comment by artplan1** [comment]
seems like bundle cache is filling, but no results on unpack 🤔

**Comment by excid3** [comment]
Looks like you got it working now?

**Comment by artplan1** [comment]
> Looks like you got it working now?

something is wrong with cache/bundler paths in `ruby/setup-ruby` with custom gemfile

**Comment by excid3** [comment]
Oh yeah, I saw the tests passing and though it was fixed. 😅

I just tried a change to move it to the job's `env`. May or may not work. We shall see.

**Comment by excid3** [comment]
Seems like it's still installing the gems again. Maybe that is because it isn't caching them separately and they override each other?

**Comment by artplan1** [comment]
I assume it caches `vendor/bundle` relative to  project root, but path to gemfiles in set relative to Gemfile's path, which is `gemfiles`. I'll check action code locally/my fork to see paths

**Comment by artplan1** [comment]
@excid3 setting `BUNDLE_PATH_RELATIVE_TO_CWD ` helps. now it installs gems to `./vendor/bundle`, instead of `./gemfiles/vendor/bundle` and cache works ok.

I've submitted issue with proposal to fix this in `ruby/setup-ruby` - https://github.com/ruby/setup-ruby/issues/131

**Comment by excid3** [comment]
Awesome, thanks for doing all that digging!

**Comment by artplan1** [comment]
image

🚀

**Comment by excid3** [comment]
Blazing fast! 🔥

**Comment by artplan1** [comment]
> I've submitted issue with proposal to fix this in `ruby/setup-ruby` - [ruby/setup-ruby#131](https://github.com/ruby/setup-ruby/issues/131)

they fixed it using absolute paths - https://github.com/ruby/setup-ruby/issues/131
`BUNDLE_PATH_RELATIVE_TO_CWD ` env var can be removed

**Pull request merged**
