### PR TITLE
Arguments (including tenant_id) could be passed as strings(vs integer…

### PR DESCRIPTION
**Pull request by vronin**
…s) to the server. As result it won't recognize it as not cchanged, because db will return integer. Converting both of them to strings to fix it

### CODE REVIEW

**Comment by ErwinM** [comment]
I don't really understand your code changes tbh. Can you make a failing test case to illustrate the problem you are trying to solve?

**Comment by vronin** [comment]
Erwin, I added the test.
The idea is following.

- ActiveRecord automatically converts strings to integers.
So, you can do @project.acount_id = "5" and it will be the same as @project.account_id = 5

- There are gems which use this. As example RailsAdmin gem. It sends back id's as strings. If you don't use ActsAsTenant, it will work fine (ActiveRecord will do a conversion)

- If ActsAsTenant is used, we Model_extension will intercept it before it goes to ActiveRecord. It will compare an integer coming from DB (integer variable in the code) with string coming from controller ( send(fkey)). This will return false and it will throw

- I believe the code should be acting the same way as ActiveRecord (accepting a string).

**Comment by ErwinM** [comment]
I think #116 has covered your PR as well?

**Comment by vronin** [comment]
yeap. it looks good (much cleaner solution than I had)

**Pull request closed without merging**
