### PR TITLE
Allow to Change Tenant on Models Using New with_mutable_tenant Block

### PR DESCRIPTION
**Pull request by patrotom**
I took the code from the fork from this PR: #210 I added some notes about this feature to README.md.

I want to use this new feature, but honestly, the PR #210 looks dead, so I decided to fork the repository again, take the code from https://github.com/ksouthworth/acts_as_tenant and add the required notes to README.md.

All credits for the code in this PR go to [ksouthworth](https://github.com/ksouthworth).

### CODE REVIEW

**Comment by excid3** [comment]
I feel like the name of this is a little confusing. `without_tenant` to me just feels like it would set tenant to `nil` and nothing more.

What if we called it `allow_tenant_changes` or something similar?

**Comment by patrotom** [comment]
> I feel like the name of this is a little confusing. `without_tenant` to me just feels like it would set tenant to `nil` and nothing more.
> 
> What if we called it `allow_tenant_changes` or something similar?

Actually not a bad idea. `allow_tenant_changes` sounds good. I was thinking we could use something like `with_tenant_modifications`. I am quite fond of the `with/without` prefix. What do you think?

**Comment by excid3** [comment]
Maybe `with_different_tenant` ?

**Comment by patrotom** [comment]
> Maybe `ActsAsTenant.with_mutable_tenant` ? We're already using that wording internally, and I think that makes it pretty clear for users this will temporarily allow mutation of the tenant for a record.

I agree. This is probably the best name for it so far. I will adjust the PR.

**Comment by excid3** [comment]
Thanks @patrotom 👍 

That's probably the last PR I merge before I release 1.0! 🎉

**Comment by patrotom** [comment]
Alright, I rewrote the code and changed `without_tenant!` to `with_mutable_tenant`. I also changed the structure of the added code based on the master.

I apologize for the delay. I hope we can close this PR as soon as possible. :-)

@excid3 can you, please, to the code review?

Thanks.

**Comment by Ancez** [comment]
Can we get an update on this? Is there anything I can help with to get this merged down?

**Review by Ancez — APPROVED** [review]

**Comment by patrotom** [comment]
> Can we get an update on this? Is there anything I can help with to get this merged down?

Hopefully, someone who can merge will look at it soon...

**Comment by murugaperumal-ramasamy** [comment]
@patrotom Just a thought, with the new addition of this [method](https://github.com/ErwinM/acts_as_tenant/blob/ff76d47c6719f057d6e62fb1a8fe0eec2411a221/lib/acts_as_tenant/model_extensions.rb#L84) you can achieve the without_tenant functionality by overriding the `tenant_modified?` method in your model.

cc: @excid3

**Comment by Merovex** [comment]
@excid3 could this PR get a little love? It looks like it's been ready for a couple years. Otherwise, I'll have to drop back to `belongs_to` for a few models as I have records I want to transfer between owners.

**Comment by excid3** [comment]
It has conflicts that need to be resolved, but once those are done we can merge it. If I have time today, I will try.

Had a baby recently so it's a bit hard to keep up with everything at the moment. 👶

**Comment by Merovex** [comment]
Congratulations on the baby. A different sort of commit...poop requests, etc.

**Pull request merged**
